//
//  WorkgroupAnimalNames.swift
//  iTerm2SharedARC
//
//  Created by George Nachman on 4/24/26.
//

import Foundation

// Default-name pool for new workgroup sessions. Short animal names keep
// the mode-switcher + tab-bar wireframe readable at small widths. Names
// are picked in list order (deterministic) and deduped against whatever
// the workgroup already uses, so two new sessions never share one by
// default.
enum WorkgroupAnimalNames {
    static let all: [String] = [
        String(localized: "WorkgroupAnimalNames.Fox", defaultValue: "Fox", comment: "Default name for a new workgroup session"), String(localized: "WorkgroupAnimalNames.Hen", defaultValue: "Hen", comment: "Default name for a new workgroup session"), String(localized: "WorkgroupAnimalNames.Owl", defaultValue: "Owl", comment: "Default name for a new workgroup session"), String(localized: "WorkgroupAnimalNames.Cat", defaultValue: "Cat", comment: "Default name for a new workgroup session"), String(localized: "WorkgroupAnimalNames.Dog", defaultValue: "Dog", comment: "Default name for a new workgroup session"), String(localized: "WorkgroupAnimalNames.Pig", defaultValue: "Pig", comment: "Default name for a new workgroup session"), String(localized: "WorkgroupAnimalNames.Cow", defaultValue: "Cow", comment: "Default name for a new workgroup session"), String(localized: "WorkgroupAnimalNames.Bat", defaultValue: "Bat", comment: "Default name for a new workgroup session"), String(localized: "WorkgroupAnimalNames.Bee", defaultValue: "Bee", comment: "Default name for a new workgroup session"),
        String(localized: "WorkgroupAnimalNames.Elk", defaultValue: "Elk", comment: "Default name for a new workgroup session"), String(localized: "WorkgroupAnimalNames.Doe", defaultValue: "Doe", comment: "Default name for a new workgroup session"), String(localized: "WorkgroupAnimalNames.Jay", defaultValue: "Jay", comment: "Default name for a new workgroup session"), String(localized: "WorkgroupAnimalNames.Ram", defaultValue: "Ram", comment: "Default name for a new workgroup session"), String(localized: "WorkgroupAnimalNames.Ewe", defaultValue: "Ewe", comment: "Default name for a new workgroup session"), String(localized: "WorkgroupAnimalNames.Rat", defaultValue: "Rat", comment: "Default name for a new workgroup session"), String(localized: "WorkgroupAnimalNames.Ant", defaultValue: "Ant", comment: "Default name for a new workgroup session"), String(localized: "WorkgroupAnimalNames.Yak", defaultValue: "Yak", comment: "Default name for a new workgroup session"), String(localized: "WorkgroupAnimalNames.Emu", defaultValue: "Emu", comment: "Default name for a new workgroup session"),
        String(localized: "WorkgroupAnimalNames.Ape", defaultValue: "Ape", comment: "Default name for a new workgroup session"), String(localized: "WorkgroupAnimalNames.Asp", defaultValue: "Asp", comment: "Default name for a new workgroup session"), String(localized: "WorkgroupAnimalNames.Frog", defaultValue: "Frog", comment: "Default name for a new workgroup session"), String(localized: "WorkgroupAnimalNames.Hare", defaultValue: "Hare", comment: "Default name for a new workgroup session"), String(localized: "WorkgroupAnimalNames.Wolf", defaultValue: "Wolf", comment: "Default name for a new workgroup session"), String(localized: "WorkgroupAnimalNames.Bear", defaultValue: "Bear", comment: "Default name for a new workgroup session"), String(localized: "WorkgroupAnimalNames.Deer", defaultValue: "Deer", comment: "Default name for a new workgroup session"), String(localized: "WorkgroupAnimalNames.Goat", defaultValue: "Goat", comment: "Default name for a new workgroup session"),
        String(localized: "WorkgroupAnimalNames.Lion", defaultValue: "Lion", comment: "Default name for a new workgroup session"), String(localized: "WorkgroupAnimalNames.Mole", defaultValue: "Mole", comment: "Default name for a new workgroup session"), String(localized: "WorkgroupAnimalNames.Seal", defaultValue: "Seal", comment: "Default name for a new workgroup session"), String(localized: "WorkgroupAnimalNames.Swan", defaultValue: "Swan", comment: "Default name for a new workgroup session"), String(localized: "WorkgroupAnimalNames.Crab", defaultValue: "Crab", comment: "Default name for a new workgroup session"), String(localized: "WorkgroupAnimalNames.Tuna", defaultValue: "Tuna", comment: "Default name for a new workgroup session"), String(localized: "WorkgroupAnimalNames.Lamb", defaultValue: "Lamb", comment: "Default name for a new workgroup session"), String(localized: "WorkgroupAnimalNames.Kiwi", defaultValue: "Kiwi", comment: "Default name for a new workgroup session"),
        String(localized: "WorkgroupAnimalNames.Duck", defaultValue: "Duck", comment: "Default name for a new workgroup session"), String(localized: "WorkgroupAnimalNames.Fawn", defaultValue: "Fawn", comment: "Default name for a new workgroup session"), String(localized: "WorkgroupAnimalNames.Lynx", defaultValue: "Lynx", comment: "Default name for a new workgroup session"), String(localized: "WorkgroupAnimalNames.Puma", defaultValue: "Puma", comment: "Default name for a new workgroup session"), String(localized: "WorkgroupAnimalNames.Moth", defaultValue: "Moth", comment: "Default name for a new workgroup session"), String(localized: "WorkgroupAnimalNames.Wren", defaultValue: "Wren", comment: "Default name for a new workgroup session"), String(localized: "WorkgroupAnimalNames.Mink", defaultValue: "Mink", comment: "Default name for a new workgroup session"), String(localized: "WorkgroupAnimalNames.Toad", defaultValue: "Toad", comment: "Default name for a new workgroup session"),
        String(localized: "WorkgroupAnimalNames.Mule", defaultValue: "Mule", comment: "Default name for a new workgroup session"), String(localized: "WorkgroupAnimalNames.Boar", defaultValue: "Boar", comment: "Default name for a new workgroup session"), String(localized: "WorkgroupAnimalNames.Crow", defaultValue: "Crow", comment: "Default name for a new workgroup session"), String(localized: "WorkgroupAnimalNames.Dove", defaultValue: "Dove", comment: "Default name for a new workgroup session"), String(localized: "WorkgroupAnimalNames.Otter", defaultValue: "Otter", comment: "Default name for a new workgroup session"), String(localized: "WorkgroupAnimalNames.Skunk", defaultValue: "Skunk", comment: "Default name for a new workgroup session"), String(localized: "WorkgroupAnimalNames.Koala", defaultValue: "Koala", comment: "Default name for a new workgroup session"),
        String(localized: "WorkgroupAnimalNames.Llama", defaultValue: "Llama", comment: "Default name for a new workgroup session"), String(localized: "WorkgroupAnimalNames.Camel", defaultValue: "Camel", comment: "Default name for a new workgroup session"), String(localized: "WorkgroupAnimalNames.Eagle", defaultValue: "Eagle", comment: "Default name for a new workgroup session"), String(localized: "WorkgroupAnimalNames.Goose", defaultValue: "Goose", comment: "Default name for a new workgroup session"), String(localized: "WorkgroupAnimalNames.Hyena", defaultValue: "Hyena", comment: "Default name for a new workgroup session"), String(localized: "WorkgroupAnimalNames.Sloth", defaultValue: "Sloth", comment: "Default name for a new workgroup session"), String(localized: "WorkgroupAnimalNames.Gecko", defaultValue: "Gecko", comment: "Default name for a new workgroup session"),
        String(localized: "WorkgroupAnimalNames.Panda", defaultValue: "Panda", comment: "Default name for a new workgroup session"), String(localized: "WorkgroupAnimalNames.Snake", defaultValue: "Snake", comment: "Default name for a new workgroup session"), String(localized: "WorkgroupAnimalNames.Tiger", defaultValue: "Tiger", comment: "Default name for a new workgroup session"), String(localized: "WorkgroupAnimalNames.Whale", defaultValue: "Whale", comment: "Default name for a new workgroup session"), String(localized: "WorkgroupAnimalNames.Zebra", defaultValue: "Zebra", comment: "Default name for a new workgroup session"), String(localized: "WorkgroupAnimalNames.Mouse", defaultValue: "Mouse", comment: "Default name for a new workgroup session"), String(localized: "WorkgroupAnimalNames.Horse", defaultValue: "Horse", comment: "Default name for a new workgroup session"),
    ]

    // Returns the first animal not in `taken`. If every base name is
    // taken, tries "Fox 2", "Hen 2", …, then "Fox 3", … until it finds
    // a free one.
    static func pick(taken: Set<String>) -> String {
        for name in all where !taken.contains(name) { return name }
        var suffix = 2
        while true {
            for name in all {
                let candidate = "\(name) \(suffix)"
                if !taken.contains(candidate) { return candidate }
            }
            suffix += 1
        }
    }
}
