#!/bin/bash
# Comprehensive test for DECDWL/DECDHL with various SGR attributes.
# Run: bash tests/decdwl_decdhl_sgr.sh

ESC=$'\033'
CSI="${ESC}["
RESET="${CSI}0m"

echo "=== DECDWL (ESC # 6) ==="
echo "${ESC}#6${RESET}Normal double-width"
echo "${ESC}#6${CSI}1mBold double-width${RESET}"
echo "${ESC}#6${CSI}3mItalic double-width${RESET}"
echo "${ESC}#6${CSI}1;3mBold italic double-width${RESET}"
echo "${ESC}#6${CSI}4mUnderline double-width${RESET}"
echo "${ESC}#6${CSI}2mFaint double-width${RESET}"
echo "${ESC}#6${CSI}7mReverse double-width${RESET}"
echo "${ESC}#6${CSI}9mStrikethrough double-width${RESET}"
echo "${ESC}#6${CSI}31mRed double-width${RESET}"
echo "${ESC}#6${CSI}1;4;3;31mBold underline italic red${RESET}"
echo ""

echo "=== DECDHL top (ESC # 3) + bottom (ESC # 4) ==="
echo "${ESC}#3${RESET}Normal double-height"
echo "${ESC}#4${RESET}Normal double-height"
echo "${ESC}#3${CSI}1mBold double-height"
echo "${ESC}#4${CSI}1mBold double-height${RESET}"
echo "${ESC}#3${CSI}3mItalic double-height"
echo "${ESC}#4${CSI}3mItalic double-height${RESET}"
echo "${ESC}#3${CSI}1;3mBold italic DH"
echo "${ESC}#4${CSI}1;3mBold italic DH${RESET}"
echo "${ESC}#3${CSI}4mUnderline DH"
echo "${ESC}#4${CSI}4mUnderline DH${RESET}"
echo "${ESC}#3${CSI}2mFaint double-height"
echo "${ESC}#4${CSI}2mFaint double-height${RESET}"
echo "${ESC}#3${CSI}7mReverse DH"
echo "${ESC}#4${CSI}7mReverse DH${RESET}"
echo "${ESC}#3${CSI}9mStrikethrough DH"
echo "${ESC}#4${CSI}9mStrikethrough DH${RESET}"
echo ""

echo "=== DECDHL with colors ==="
echo "${ESC}#3${CSI}31mRed${CSI}32m Green${CSI}34m Blue"
echo "${ESC}#4${CSI}31mRed${CSI}32m Green${CSI}34m Blue${RESET}"
echo "${ESC}#3${CSI}38;5;208mOrange 256-color"
echo "${ESC}#4${CSI}38;5;208mOrange 256-color${RESET}"
echo "${ESC}#3${CSI}38;2;128;0;255mPurple 24-bit"
echo "${ESC}#4${CSI}38;2;128;0;255mPurple 24-bit${RESET}"
echo ""

echo "=== DECDHL with emoji ==="
echo "${ESC}#3Hello 🌍 World 🎉"
echo "${ESC}#4Hello 🌍 World 🎉"
echo "${ESC}#3${CSI}1mBold emoji 🚀✨"
echo "${ESC}#4${CSI}1mBold emoji 🚀✨${RESET}"
echo ""

echo "=== DECSWL (ESC # 5) reset ==="
echo "${ESC}#6This was double-width"
echo "${ESC}#5This is back to normal"
echo ""

echo "=== Mixed lines ==="
echo "Normal line"
echo "${ESC}#6Double-width line"
echo "${ESC}#3Double-height top"
echo "${ESC}#4Double-height bottom"
echo "Normal again"
echo ""

echo "=== Fullwidth characters on DECDWL ==="
echo "${ESC}#6Ｈｅｌｌｏ"
echo ""

echo "=== CJK on DECDHL ==="
echo "${ESC}#3漢字テスト"
echo "${ESC}#4漢字テスト"
echo ""

echo "=== Long line wrapping on DECDWL ==="
echo "${ESC}#6ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789abcdefghijklmnop"
echo ""

echo "=== Background colors ==="
echo "${ESC}#3${CSI}41m Red bg ${CSI}42m Green bg ${CSI}44m Blue bg ${RESET}"
echo "${ESC}#4${CSI}41m Red bg ${CSI}42m Green bg ${CSI}44m Blue bg ${RESET}"
echo ""

echo "Done. Scroll up to verify all styles render correctly."
echo "Toggle GPU renderer (Preferences > Advanced) to compare."
