#!/bin/bash
if [ $# -eq 0 ]; then
  echo "Usage: image.sh filename"
  exit 1
fi
for fn in "$@"
do
  rc=$?
  if [[ $rc == 0 ]] ; then
    printf '\033]50;BeginFile='"$fn"'\n'
    wc -c "$fn" | awk '{print $1}'
    echo auto
    echo auto
    printf '\a'
    base64 < "$fn"
    printf '\033]50;EndFile\a'
  else
    echo File $fn does not exist.
  fi
done
