#!/bin/bash
if [ ! -t 0 ]; then
  CONTENTS=$(cat | base64)
  printf '\033]1337;File=;\n'
  echo -n "$CONTENTS" | base64 -D | wc -c | awk '{printf "size=%d",$1}'
  printf ";inline=1"
  printf ":"
  echo -n "$CONTENTS"
  printf '\a\n'
  exit 0
fi
if [ $# -eq 0 ]; then
  echo "Usage: imgcat filename ..."
  echo "   or: cat filename | imgcat"
  exit 1
fi
for fn in "$@"
do
  if [ -r $fn ] ; then
    printf '\033]1337;File=name='`echo -n "$fn" | base64`";"
    wc -c "$fn" | awk '{printf "size=%d",$1}'
    printf ";inline=1"
    printf ":"
    base64 < "$fn"
    printf '\a\n'
  else
    echo File $fn does not exist.
  fi
done
