//
//  PasswordManagerDataSource.swift
//  iTerm2SharedARC
//
//  Created by George Nachman on 3/18/22.
//

import Foundation

@objc
protocol PasswordManagerAccount: AnyObject {
    @objc var accountName: String { get }
    @objc var userName: String { get }
    @objc var displayString: String { get }
    @objc var hasOTP: Bool { get }
    @objc var sendOTP: Bool { get }
    /// Vault/source hint (e.g. "Classic", "Nested") for host label formatting.
    /// Return nil when the data source has no such concept.
    @objc var sourceLabel: String? { get }

    @objc(fetchPasswordWithContext:completion:)
    func fetchPassword(context: RecipeExecutionContext,
                       _ completion: @escaping (String?, String?, Error?) -> ())

    @objc(setPasswordWithContext:password:completion:)
    func set(context: RecipeExecutionContext,
             password: String,
             completion: @escaping (Error?)-> ())

    @objc(deleteWithContext:completion:)
    func delete(context: RecipeExecutionContext,
                _ completion: @escaping (Error?) -> ())

    @objc(matchesFilter:) func matches(filter: String) -> Bool
}

/// Shared “Account (Classic)” / “Account (Nested)” display formatting for list UI.
@objc(iTermPasswordManagerAccountFormatting)
class iTermPasswordManagerAccountFormatting: NSObject {
    @objc(displayNameForAccountName:sourceLabel:)
    static func displayName(accountName: String, sourceLabel: String?) -> String {
        if let source = sourceLabel?.trimmingCharacters(in: .whitespacesAndNewlines), !source.isEmpty {
            return "\(accountName) (\(source))"
        }
        return accountName
    }
}

@objc
protocol PasswordManagerDataSource: AnyObject {
    func fetchAccounts(context: RecipeExecutionContext, completion: @escaping ([PasswordManagerAccount]) -> ())
    var autogeneratedPasswordsOnly: Bool { get }
    func checkAvailability() -> Bool

    /// Add Account checkboxes declared by the data source. Return nil when there are none.
    @objc var addAccountToggleDescriptions: [[String: Any]]? { get }

    /// Adds an account. `flags` carries the Add Account toggle states (see
    /// `addAccountToggleDescriptions`); data sources without toggles ignore it.
    @objc(addUserName:accountName:password:flags:context:completion:)
    func add(userName: String,
             accountName: String,
             password: String,
             flags: [String: Bool],
             context: RecipeExecutionContext,
             completion: @escaping (PasswordManagerAccount?, Error?) -> ())

    func resetErrors()
    func reload(_ completion: () -> ())
    func consolidateAvailabilityChecks(_ block: () -> ())

    @objc(toggleShouldSendOTPWithContext:forAccount:completion:)
    func toggleShouldSendOTP(context: RecipeExecutionContext,
                             account: PasswordManagerAccount,
                             completion: @escaping (PasswordManagerAccount?, Error?) -> ())

    @objc var canResetConfiguration: Bool { get }
    @objc func resetConfiguration()
    @objc var name: String { get }
    @objc var supportsMultipleAccounts: Bool { get }
    @objc(switchAccountWithCompletion:) func switchAccount(completion: @escaping () -> ())
}

@objc(iTermAdapterCapabilities)
protocol AdapterCapabilities: AnyObject {
    @objc var hasSettingsFields: Bool { get }
    @objc var customCommandDescriptions: [[String: String]]? { get }
    @objc func runCustomCommand(_ name: String, window: NSWindow?, completion: @escaping (String?, Error?) -> Void)
    @objc func settingsValue(forKey key: String) -> String?
    @objc func setSettingsValue(_ value: String, forKey key: String)
    @objc var settingsFieldDescriptions: [[String: Any]]? { get }
}

extension PasswordManagerAccount {
    func _matches(filter: String) -> Bool {
        if filter.isEmpty {
            return true
        }
        return [accountName, userName].anySatisfies {
            $0.containsCaseInsensitive(filter)
        }
    }
}

