//
//  PasswordManagerDataSource.swift
//  iTerm2SharedARC
//
//  Created by George Nachman on 3/18/22.
//

import Foundation

@objc
protocol PasswordManagerAccount: AnyObject {
    @objc var accountName: String { get }
    @objc var userName: String { get }
    @objc var displayString: String { get }
    @objc var hasOTP: Bool { get }
    @objc var sendOTP: Bool { get }
    /// Vault/source hint (e.g. "Classic", "Nested") for host label formatting.
    /// Return nil when the data source has no such concept.
    @objc var sourceLabel: String? { get }

    @objc(fetchPasswordWithContext:completion:)
    func fetchPassword(context: RecipeExecutionContext,
                       _ completion: @escaping (String?, String?, Error?) -> ())

    @objc(setPasswordWithContext:password:completion:)
    func set(context: RecipeExecutionContext,
             password: String,
             completion: @escaping (Error?)-> ())

    @objc(deleteWithContext:completion:)
    func delete(context: RecipeExecutionContext,
                _ completion: @escaping (Error?) -> ())

    /// Updates the account's name, user name, and optionally password in place, preserving
    /// other fields (OTP, custom fields). Each argument is nil for a field the user did not
    /// change, so an unchanged field is never rewritten (important when the displayed value is
    /// derived rather than the stored value, e.g. Keeper's suffix-stripped user name). Only
    /// called when the data source's `supportsInPlaceEdit` is true; data sources without
    /// in-place edit complete with an error.
    @objc(editInPlaceWithAccountName:userName:password:context:completion:)
    func editInPlace(accountName: String?,
                     userName: String?,
                     password: String?,
                     context: RecipeExecutionContext,
                     completion: @escaping (Error?) -> ())

    @objc(matchesFilter:) func matches(filter: String) -> Bool
}

/// Shared “Account (Classic)” / “Account (Nested)” display formatting for list UI.
@objc(iTermPasswordManagerAccountFormatting)
class iTermPasswordManagerAccountFormatting: NSObject {
    @objc(displayNameForAccountName:sourceLabel:)
    static func displayName(accountName: String, sourceLabel: String?) -> String {
        if let source = sourceLabel?.trimmingCharacters(in: .whitespacesAndNewlines), !source.isEmpty {
            return "\(accountName) (\(source))"
        }
        return accountName
    }
}

@objc
protocol PasswordManagerDataSource: AnyObject {
    func fetchAccounts(context: RecipeExecutionContext, completion: @escaping ([PasswordManagerAccount]) -> ())
    var autogeneratedPasswordsOnly: Bool { get }
    func checkAvailability() -> Bool

    /// Warms any expensive availability inputs off the main thread, then calls `completion` on
    /// the main thread. The host calls this before a synchronous `checkAvailability` so that
    /// check reads warm caches instead of blocking the run loop (e.g. 1Password resolving the
    /// `op` CLI version). Sources with nothing to warm call `completion` immediately.
    @objc func prepareAvailability(_ completion: @escaping () -> ())

    /// Add Account checkboxes declared by the data source. Return nil when there are none.
    @objc var addAccountToggleDescriptions: [[String: Any]]? { get }

    /// True when the data source can edit a record's fields in place (via `editInPlace`),
    /// so the host renames without delete-then-re-add. False data sources keep the old path.
    @objc var supportsInPlaceEdit: Bool { get }

    /// True when the data source can change the password of an existing record. Some can
    /// create with a password but cannot securely change one (e.g. 1Password on older CLIs);
    /// the Edit panel disables its password field when this is false.
    @objc var canEditPassword: Bool { get }

    /// True when Add must be given a non-empty password. Sources that write the password field
    /// verbatim (e.g. 1Password's create template) would otherwise store an empty password;
    /// sources that omit an empty password (Keeper, Keychain, LastPass) return false.
    @objc var requiresPasswordForAdd: Bool { get }

    /// Adds an account. `flags` carries the Add Account toggle states (see
    /// `addAccountToggleDescriptions`); data sources without toggles ignore it.
    @objc(addUserName:accountName:password:flags:context:completion:)
    func add(userName: String,
             accountName: String,
             password: String,
             flags: [String: Bool],
             context: RecipeExecutionContext,
             completion: @escaping (PasswordManagerAccount?, Error?) -> ())

    func resetErrors()
    func reload(_ completion: () -> ())
    func consolidateAvailabilityChecks(_ block: () -> ())

    @objc(toggleShouldSendOTPWithContext:forAccount:completion:)
    func toggleShouldSendOTP(context: RecipeExecutionContext,
                             account: PasswordManagerAccount,
                             completion: @escaping (PasswordManagerAccount?, Error?) -> ())

    @objc var canResetConfiguration: Bool { get }
    @objc func resetConfiguration()
    @objc var name: String { get }
    @objc var supportsMultipleAccounts: Bool { get }
    @objc(switchAccountWithCompletion:) func switchAccount(completion: @escaping () -> ())
}

@objc(iTermAdapterCapabilities)
protocol AdapterCapabilities: AnyObject {
    @objc var hasSettingsFields: Bool { get }
    @objc var customCommandDescriptions: [[String: String]]? { get }
    @objc func runCustomCommand(_ name: String, window: NSWindow?, completion: @escaping (String?, Error?) -> Void)
    @objc func settingsValue(forKey key: String) -> String?
    @objc func setSettingsValue(_ value: String, forKey key: String)
    @objc var settingsFieldDescriptions: [[String: Any]]? { get }
}

extension PasswordManagerAccount {
    func _matches(filter: String) -> Bool {
        if filter.isEmpty {
            return true
        }
        return [accountName, userName].anySatisfies {
            $0.containsCaseInsensitive(filter)
        }
    }
}

