#!/usr/bin/env osascript
on run argv
	tell application "iTerm2"
		if number of items in argv is 1 then
			launch API script named (item 1 of argv)
		else if number of items in argv is 2 then
			launch API script named (item 1 of argv) arguments (item 2 of argv)
		else
			log "Usage: it2run MyScript.py ['arg1 arg2...']"
		end if
	end tell
end run

