//
//  VT100WorkingDirectory.m
//  iTerm
//
//  Created by George Nachman on 12/20/13.
//
//

#import "VT100WorkingDirectory.h"
#import "NSObject+iTerm.h"

static NSString *const kWorkingDirectoryStateWorkingDirectoryKey = @"Working Directory";
static NSString *const kWorkingDirectoryGuidKey = @"Guid";

@implementation VT100WorkingDirectory {
    VT100WorkingDirectory *_doppelganger;
    __weak VT100WorkingDirectory *_progenitor;
    BOOL _isDoppelganger;
    NSString *_guid;
}

@synthesize entry;
@synthesize guid = _guid;

- (instancetype)initWithDictionary:(NSDictionary *)dict {
    self = [self initWithDirectory:dict[kWorkingDirectoryStateWorkingDirectoryKey]];
    if (self) {
        NSString *savedGuid = dict[kWorkingDirectoryGuidKey];
        if (savedGuid.length > 0) {
            _guid = [savedGuid copy];
        }
        // else keep the guid generated by initWithDirectory:
    }
    return self;
}

- (instancetype)initWithDirectory:(NSString *)directory {
    self = [super init];
    if (self) {
        _workingDirectory = [directory copy];
        _guid = [[NSUUID UUID] UUIDString];
    }
    return self;
}

- (NSString *)description {
    return [NSString stringWithFormat:@"<%@: %p workingDirectory=%@ interval=%@ %@>",
            self.class, self, self.workingDirectory, self.entry.interval,
            _isDoppelganger ? @"IsDop" : @"NotDop"];
}

#pragma mark - IntervalTreeObject

- (NSDictionary *)dictionaryValue {
    NSMutableDictionary *dict = [NSMutableDictionary dictionary];
    if (self.workingDirectory) {
        dict[kWorkingDirectoryStateWorkingDirectoryKey] = self.workingDirectory;
    }
    if (_guid) {
        dict[kWorkingDirectoryGuidKey] = _guid;
    }
    return dict;
}

- (nonnull NSDictionary *)dictionaryValueWithTypeInformation {
    return @{ @"class": NSStringFromClass(self.class),
              @"value": [self dictionaryValue] };
}

- (NSString *)shortDebugDescription {
    return [NSString stringWithFormat:@"[Dir %@]", self.workingDirectory];
}

- (NSString *)stableIdentifier {
    return _guid;
}

- (nonnull id<IntervalTreeObject>)doppelganger {
    @synchronized ([VT100WorkingDirectory class]) {
        assert(!_isDoppelganger);
        if (!_doppelganger) {
            _doppelganger = [self copyOfIntervalTreeObject];
            _doppelganger->_progenitor = self;
            _doppelganger->_isDoppelganger = YES;
        }
        return _doppelganger;
    }
}

- (id<IntervalTreeObject>)progenitor {
    @synchronized ([VT100WorkingDirectory class]) {
        return _progenitor;
    }
}

- (instancetype)copyOfIntervalTreeObject {
    VT100WorkingDirectory *copy = [[VT100WorkingDirectory alloc] initWithDirectory:self.workingDirectory];
    copy->_guid = [_guid copy];
    return copy;
}

@end
