//
//  ChatBlobWireEncoder.swift
//  iTerm2
//
//  Freezes one completed conversational ROUND into its protocol's request-shape
//  wire form, which is stored verbatim in a ChatBlob and later stitched (in
//  order) into a request by the assembler. A round is `[user message, novel item
//  0 … novel item m]`: the user turn plus every novel agent/tool item produced
//  until the agent's turn ended (the only safe capture point, since you can't
//  have two consecutive user messages).
//
//  The encoder reuses each vendor builder's EXACT per-message conversion, so the
//  bytes we freeze are the bytes that vendor already accepted. Crucially it runs
//  the builder's cross-message passes (for Anthropic: enforceToolUseAdjacency +
//  coalesceConsecutiveAssistantMessages) ONCE, here, at capture time; the frozen
//  result never needs them again, so reconstruction is pure concat + envelope and
//  the whole repair/coalesce/adjacency machinery is retired for blob-native chats.
//
//  This is sound because a round is bounded by user messages and ends with a
//  complete agent turn, which makes the conversion COMPOSITIONAL over rounds:
//  convert(r1 + r2 + …) == convert(r1) + convert(r2) + …  (a tool_use/tool_result
//  pair never spans a round, and a round boundary is always assistant→user so two
//  assistant messages never coalesce across it). Stitching the frozen rounds is
//  therefore byte-equivalent to serializing the whole conversation at once. See
//  ChatBlobWireEncoderTests, which pins that invariant.
//
//  Note for the assembler (Phase 3): stitch payloads at the JSON level (merge the
//  arrays of message objects), NOT by decoding into the typed wire structs. Some
//  wire types are encode-only (e.g. CompletionsMessage emits role "tool" but
//  cannot decode it back), so a typed round-trip would fail; JSON-level merge is
//  both protocol-agnostic and byte-faithful.
//
//  What is NOT included (all envelope, regenerated by the assembler at send time):
//  the system prompt, tools, the volatile per-turn context, protocol cache
//  markers (Anthropic markLastMessageForCaching), and request-level params like
//  previous_response_id. Secrets never appear here: API keys live in headers/URL,
//  never in message content.
//

import Foundation

enum ChatBlobWireEncoderError: Error, CustomStringConvertible {
    /// This protocol's wire encoder is not implemented yet.
    case unsupportedProtocol(iTermAIAPI)

    var description: String {
        switch self {
        case .unsupportedProtocol(let api):
            return "ChatBlobWireEncoder has no encoder for api \(api.rawValue)"
        }
    }
}

enum ChatBlobWireEncoder {
    /// Freeze a completed round into the `ChatBlob.payload` bytes for `api`: a JSON
    /// array of that protocol's request-shape wire messages. Envelope and cache
    /// markers are excluded (the assembler adds them). Throws
    /// `unsupportedProtocol` for a protocol whose encoder isn't built yet.
    ///
    /// `modelName` is the chat's bound model, needed by protocols whose wire form
    /// is model-dependent (Gemini injects a thought-signature fallback token only
    /// on models that require signatures); the capture site has it. It is ignored
    /// by model-independent protocols.
    ///
    /// `hostedTools` must be the SAME hosted-tools set the live request used, so
    /// the frozen bytes match it. The Responses builder's user-attachment encoding
    /// is hostedTools-dependent: a `.fileID` subpart is dropped from content when
    /// code interpreter is on (the file rides the tools envelope instead) but
    /// emitted as an `input_file` in content when it is off. Passing an empty set
    /// here would freeze a fileID as content for a code-interpreter chat, which the
    /// live request never sent and which can 400 on replay. Ignored by protocols
    /// whose message encoding doesn't depend on hosted tools.
    static func encodeRound(_ round: [LLM.Message],
                            api: iTermAIAPI,
                            modelName: String? = nil,
                            hostedTools: HostedTools = HostedTools()) throws -> Data {
        switch api {
        case .anthropic:
            // convertMessages applies the same per-message mapping, tool-pair
            // adjacency, and assistant coalescing the live request uses; the
            // result is the unmarked message array for this round. Encode with
            // .sortedKeys to MATCH AnthropicRequestBuilder.body() (which sorts keys
            // because Anthropic's prompt cache is a byte-prefix match): otherwise a
            // turn's frozen bytes would differ from the sorted bytes it was first
            // sent with, and the replayed prefix would miss the cache.
            return try sortedKeysEncoder.encode(AnthropicRequestBuilder.convertMessages(round))
        case .chatCompletions:
            // The chat-completions builder is a bare per-message map (no
            // cross-message reshaping), so freezing a round is the same map. Two
            // consecutive assistant messages (a text preamble then a tool_calls
            // message) are sent as-is, exactly as the live request does.
            return try encoder.encode(round.compactMap { CompletionsMessage($0) })
        case .llama:
            // Same map, but the live llama builder additionally collapses adjacent
            // text parts within an array-content message (llama rejects multiple
            // text parts). Reuse the builder's EXACT joinText pass so the frozen
            // bytes match what llama already accepted; without it a round with
            // multi-text-part content (e.g. a preamble + a .code attachment) would
            // replay as multiple text parts and be rejected.
            return try encoder.encode(
                round.compactMap { CompletionsMessage($0) }.map { LlamaBodyRequestBuilder.joinText($0) })
        case .earlyO1:
            // Same map, but o1 replaces the system role with user. A round never
            // contains a system message (system is envelope), so this is a no-op
            // here; applied anyway to stay faithful to the live request.
            let mapped = round.map { message -> LLM.Message in
                guard message.role == .system else { return message }
                var temp = message
                temp.role = .user
                return temp
            }
            return try encoder.encode(mapped.compactMap { CompletionsMessage($0) })
        case .deepSeek:
            // Pure per-message map to DeepSeek's own wire Message (content is a
            // plain string, tool_calls array, and reasoning_content echoed on
            // assistant turns). No cross-message reshaping.
            return try encoder.encode(round.compactMap { DeepSeekRequestBuilder.Message($0) })
        case .gemini:
            // Gemini's conversion (role mapping, thoughtSignature fallback
            // injection, and coalescingConsecutiveRoles) lives in the builder init
            // and depends on the model (whether it requires thought signatures),
            // so construct the real builder for this round and freeze its
            // contents. The fallback token, when injected, is thus frozen exactly
            // as the live request sent it.
            return try encoder.encode(
                GeminiRequestBuilder(messages: round, functions: [],
                                     hostedTools: HostedTools(), modelName: modelName).contents)
        case .responses:
            // One message maps to MULTIPLE input items (reasoning items precede
            // the function call they produced; a user turn becomes a message
            // item). transform is per-message and emits the full-replay shape
            // independent of previous_response_id (which only strips the list
            // later, in body()), so freezing a round is flatMap(transform). Pass
            // the live hostedTools: transform's `.fileID` attachment branch depends
            // on codeInterpreter (dropped from content when on, emitted as
            // input_file when off), so the frozen content must match what the live
            // request actually sent.
            return try sortedKeysEncoder.encode(round.flatMap {
                ResponsesBodyRequestBuilder.transform(message: $0, hostedTools: hostedTools)
            })
        case .completions, .appleIntelligence:
            throw ChatBlobWireEncoderError.unsupportedProtocol(api)
        @unknown default:
            throw ChatBlobWireEncoderError.unsupportedProtocol(api)
        }
    }

    // A single shared encoder. JSONEncoder is deterministic for a given build, so
    // freezing the round once and re-serializing the stitched prefix yields stable
    // bytes turn over turn (the same property the shipped Anthropic cache fix
    // already relies on).
    private static let encoder = JSONEncoder()

    // The Anthropic and Responses builders serialize with .sortedKeys (their
    // prompt caches are byte-prefix matches and tool/schema dict order is
    // otherwise random per process), so their blobs must too, or a turn's frozen
    // bytes would differ from the sorted bytes it was first sent with. Every other
    // builder uses a plain JSONEncoder, so their blobs use `encoder` above.
    private static let sortedKeysEncoder: JSONEncoder = {
        let e = JSONEncoder()
        e.outputFormatting = [.sortedKeys]
        return e
    }()
}
