//
//  ChatBlobWireEncoder.swift
//  iTerm2
//
//  Freezes one completed conversational ROUND into its protocol's request-shape
//  wire form, which is stored verbatim in a ChatBlob and later stitched (in
//  order) into a request by the assembler. A round is `[user message, novel item
//  0 … novel item m]`: the user turn plus every novel agent/tool item produced
//  until the agent's turn ended (the only safe capture point, since you can't
//  have two consecutive user messages).
//
//  The encoder reuses each vendor builder's EXACT per-message conversion, so the
//  bytes we freeze are the bytes that vendor already accepted. Crucially it runs
//  the builder's cross-message passes (for Anthropic: enforceToolUseAdjacency +
//  coalesceConsecutiveAssistantMessages) ONCE, here, at capture time; the frozen
//  result never needs them again, so reconstruction is pure concat + envelope and
//  the whole repair/coalesce/adjacency machinery is retired for blob-native chats.
//
//  This is sound because a round is bounded by user messages and ends with a
//  complete agent turn, which makes the conversion COMPOSITIONAL over rounds:
//  convert(r1 + r2 + …) == convert(r1) + convert(r2) + …  (a tool_use/tool_result
//  pair never spans a round, and a round boundary is always assistant→user so two
//  assistant messages never coalesce across it). Stitching the frozen rounds is
//  therefore byte-equivalent to serializing the whole conversation at once. See
//  ChatBlobWireEncoderTests, which pins that invariant.
//
//  Note for the assembler (Phase 3): stitch payloads at the JSON level (merge the
//  arrays of message objects), NOT by decoding into the typed wire structs. Some
//  wire types are encode-only (e.g. CompletionsMessage emits role "tool" but
//  cannot decode it back), so a typed round-trip would fail; JSON-level merge is
//  both protocol-agnostic and byte-faithful.
//
//  What is NOT included (all envelope, regenerated by the assembler at send time):
//  the system prompt, tools, the volatile per-turn context, protocol cache
//  markers (Anthropic markLastMessageForCaching), and request-level params like
//  previous_response_id. Secrets never appear here: API keys live in headers/URL,
//  never in message content.
//

import Foundation

enum ChatBlobWireEncoderError: Error, CustomStringConvertible {
    /// This protocol's wire encoder is not implemented yet.
    case unsupportedProtocol(iTermAIAPI)

    var description: String {
        switch self {
        case .unsupportedProtocol(let api):
            return "ChatBlobWireEncoder has no encoder for api \(api.rawValue)"
        }
    }
}

enum ChatBlobWireEncoder {
    /// Freeze a completed round into the `ChatBlob.payload` bytes for `api`: a JSON
    /// array of that protocol's request-shape wire messages. Envelope and cache
    /// markers are excluded (the assembler adds them). Throws
    /// `unsupportedProtocol` for a protocol whose encoder isn't built yet.
    static func encodeRound(_ round: [LLM.Message], api: iTermAIAPI) throws -> Data {
        switch api {
        case .anthropic:
            // convertMessages applies the same per-message mapping, tool-pair
            // adjacency, and assistant coalescing the live request uses; the
            // result is the unmarked message array for this round.
            return try encoder.encode(AnthropicRequestBuilder.convertMessages(round))
        case .chatCompletions, .llama:
            // Both builders are a pure per-message map (no cross-message
            // reshaping), so freezing a round is the same map. Two consecutive
            // assistant messages (a text preamble then a tool_calls message) are
            // sent as-is, exactly as the live request does.
            return try encoder.encode(round.compactMap { CompletionsMessage($0) })
        case .earlyO1:
            // Same map, but o1 replaces the system role with user. A round never
            // contains a system message (system is envelope), so this is a no-op
            // here; applied anyway to stay faithful to the live request.
            let mapped = round.map { message -> LLM.Message in
                guard message.role == .system else { return message }
                var temp = message
                temp.role = .user
                return temp
            }
            return try encoder.encode(mapped.compactMap { CompletionsMessage($0) })
        case .completions, .responses, .gemini, .deepSeek, .appleIntelligence:
            throw ChatBlobWireEncoderError.unsupportedProtocol(api)
        @unknown default:
            throw ChatBlobWireEncoderError.unsupportedProtocol(api)
        }
    }

    // A single shared encoder. JSONEncoder is deterministic for a given build, so
    // freezing the round once and re-serializing the stitched prefix yields stable
    // bytes turn over turn (the same property the shipped Anthropic cache fix
    // already relies on).
    private static let encoder = JSONEncoder()
}
