//
//  VT100RemoteHost.m
//  iTerm
//
//  Created by George Nachman on 12/20/13.
//
//

#import "VT100RemoteHost.h"
#import "DebugLogging.h"
#import "NSDictionary+iTerm.h"
#import "NSHost+iTerm.h"
#import "NSObject+iTerm.h"

static NSString *const kRemoteHostHostNameKey = @"Host name";
static NSString *const kRemoteHostUserNameKey = @"User name";
static NSString *const kRemoteHostGuidKey = @"Guid";
static NSString *const kRemoteHostLocalityKey = @"Locality";

@implementation VT100RemoteHost {
    VT100RemoteHost *_doppelganger;
    __weak VT100RemoteHost *_progenitor;
    BOOL _isDoppelganger;
    NSString *_guid;
}

@synthesize entry;
@synthesize username = _username;
@synthesize hostname = _hostname;
@synthesize guid = _guid;
@synthesize localityState = _localityState;

- (instancetype)initWithUsername:(NSString *)username hostname:(NSString *)hostname {
    return [self initWithUsername:username
                        hostname:hostname
                        locality:VT100RemoteHostLocalityUnknown];
}

- (instancetype)initWithUsername:(NSString *)username
                        hostname:(NSString *)hostname
                        locality:(VT100RemoteHostLocality)locality {
    self = [super init];
    if (self) {
        _username = [username copy];
        _hostname = [hostname copy];
        _localityState = locality;
        _guid = [[NSUUID UUID] UUIDString];
    }
    return self;
}

- (instancetype)initWithDictionary:(NSDictionary *)dict {
    // Absent locality key (legacy data) deserializes as unknown.
    NSNumber *locality = [NSNumber castFrom:dict[kRemoteHostLocalityKey]];
    self = [self initWithUsername:dict[kRemoteHostUserNameKey]
                         hostname:dict[kRemoteHostHostNameKey]
                         locality:locality ? locality.integerValue : VT100RemoteHostLocalityUnknown];
    if (self) {
        NSString *savedGuid = dict[kRemoteHostGuidKey];
        if (savedGuid.length > 0) {
            _guid = [savedGuid copy];
        }
        // else keep the guid generated by initWithUsername:hostname:locality:
    }
    return self;
}

+ (instancetype)localhost {
    VT100RemoteHost *localhost = [[self alloc] initWithUsername:NSUserName()
                                                       hostname:[NSHost fullyQualifiedDomainName]
                                                       locality:VT100RemoteHostLocalityLocalhost];
    return localhost;
}

+ (VT100RemoteHostLocality)localityForIsLocalhostVariableValue:(id)value {
    NSNumber *number = [NSNumber castFrom:value];
    if (!number) {
        // Unset/unknown: the consumer falls back to the legacy hostname compare.
        return VT100RemoteHostLocalityUnknown;
    }
    return number.boolValue ? VT100RemoteHostLocalityLocalhost : VT100RemoteHostLocalityRemote;
}

- (NSString *)description {
    return [NSString stringWithFormat:@"<%@: %p hostname=%@ username=%@ doppelganger=%p (%@) progenitor=%p>",
            self.class, self, self.hostname, self.username, _doppelganger, _isDoppelganger ? @"IsDop" : @"NotDop", _progenitor];
}

- (BOOL)isEqualToRemoteHost:(nullable id<VT100RemoteHostReading>)other {
    if (_localityState == VT100RemoteHostLocalityLocalhost &&
        other.localityState == VT100RemoteHostLocalityLocalhost) {
        // Both are known to be the local machine. The hostname may have
        // drifted (a network change can rename the local .local host), but
        // it's the same host. Compare only the user so that, e.g.,
        // me@localhost and root@localhost (after su) remain distinct for the
        // per-host key-mapping state stack.
        return [_username isEqualToString:other.username];
    }
    return ([_hostname isEqualToString:other.hostname] &&
            [_username isEqualToString:other.username]);
}

- (NSString *)usernameAndHostname {
    return [NSString stringWithFormat:@"%@@%@", _username, _hostname];
}

- (BOOL)isLocalhost {
    switch (_localityState) {
        case VT100RemoteHostLocalityLocalhost:
            return YES;
        case VT100RemoteHostLocalityRemote:
            return NO;
        case VT100RemoteHostLocalityUnknown:
            break;
    }
    // Legacy fallback for hosts with no stamped locality (deserialized from an
    // older format). Comparing the recorded name against the live local name
    // is fragile across network-driven hostname changes, which is exactly why
    // freshly reported hosts carry an explicit locality instead.
    NSString *localHostName = [NSHost fullyQualifiedDomainName];
    DLog(@"localHostName=%@, VT100RemoteHost.hostname=%@", localHostName, self.hostname);
    return [localHostName isEqualToString:self.hostname];
}

- (BOOL)isRemoteHost {
    return !self.isLocalhost;
}

#pragma mark - IntervalTreeObject

- (NSDictionary *)dictionaryValue {
    NSDictionary *dict =
        @{ kRemoteHostHostNameKey: _hostname ?: [NSNull null],
           kRemoteHostUserNameKey: _username ?: [NSNull null],
           kRemoteHostGuidKey: _guid ?: [NSNull null],
           kRemoteHostLocalityKey: @(_localityState) };
    return [dict dictionaryByRemovingNullValues];
}

- (instancetype)copyOfIntervalTreeObject {
    VT100RemoteHost *copy = [[VT100RemoteHost alloc] initWithUsername:self.username
                                                            hostname:self.hostname
                                                            locality:self.localityState];
    copy->_guid = [_guid copy];
    return copy;
}

- (nonnull NSDictionary *)dictionaryValueWithTypeInformation { 
    return @{ @"class": NSStringFromClass(self.class),
              @"value": [self dictionaryValue] };
}

- (NSString *)shortDebugDescription {
    return [NSString stringWithFormat:@"[RemoteHost %@@%@]", _username, _hostname];
}

- (NSString *)stableIdentifier {
    return _guid;
}

- (id<IntervalTreeObject>)doppelganger {
    @synchronized ([VT100RemoteHost class]) {
        assert(!_isDoppelganger);
        if (!_doppelganger) {
            _doppelganger = [self copyOfIntervalTreeObject];
            _doppelganger->_isDoppelganger = YES;
            _doppelganger->_progenitor = self;
        }
        return _doppelganger;
    }
}

- (id<IntervalTreeObject>)progenitor {
    @synchronized ([VT100RemoteHost class]) {
        return _progenitor;
    }
}

@end
