#!/bin/bash

function die {
  echo $1
  exit
}

branch() {
  local output=$(git symbolic-ref -q --short HEAD)
    if [ $? -eq 0 ]; then
        echo "${output}"
    fi
}

set -x

# The shell_integration Makefile uses envsubst (from gettext) to embed it2.py into
# each script. Homebrew installs gettext keg-only, so put its bin on PATH.
GETTEXT_BIN=$(brew --prefix gettext 2>/dev/null)/bin
test -d "$GETTEXT_BIN" && PATH="$GETTEXT_BIN:$PATH"
command -v envsubst >/dev/null || die "envsubst not found; run 'make setup' (installs gettext)"

SUBMODULE=$PWD/submodules/iTerm2-shell-integration
test -d $SUBMODULE || die No $SUBMODULE directory
pushd $SUBMODULE
if [ $(branch) != main ]; then
  echo "Not on main. The current branch is $(branch)."
fi
popd

(cd submodules/iTerm2-shell-integration/ && make)
# The submodule's top-level Makefile only handles utilities (it2ssh). The bash
# integration script is assembled from source/bash.0, bash-preexec.sh, and
# source/bash.1 by the shell_integration/Makefile, so it has to be invoked
# separately or edits to source/bash.{0,1} silently never reach the assembled
# `bash` file (and therefore never reach Resources/).
(cd submodules/iTerm2-shell-integration/shell_integration/ && make)
cp $SUBMODULE/shell_integration/bash  Resources/shell_integration/iterm2_shell_integration.bash
cp $SUBMODULE/shell_integration/fish  Resources/shell_integration/iterm2_shell_integration.fish
cp $SUBMODULE/shell_integration/tcsh  Resources/shell_integration/iterm2_shell_integration.tcsh
cp $SUBMODULE/shell_integration/xonsh Resources/shell_integration/iterm2_shell_integration.xonsh
cp $SUBMODULE/shell_integration/zsh   Resources/shell_integration/iterm2_shell_integration.zsh
# it2.py is owned by the shell-integration repo (it is embedded into the scripts
# above and materialized on the remote). Copy it back for the app/tests.
cp $SUBMODULE/shell_integration/it2.py OtherResources/it2.py
DEST=$PWD/Resources/utilities
ALLDEST=$PWD/OtherResources/utilities

pushd $SUBMODULE/utilities
files=$(find . -type f)
tar cvfz $DEST/utilities.tgz *
echo * > $DEST/utilities-manifest.txt
cp * $ALLDEST
popd

HEADER="sources/ShellIntegration/iTermLatestVersionByShell.h"
echo "// DO NOT MODIFY - Generated by tools/copy_shell_integration.sh" > $HEADER
echo "latestVersionByShell = @{" >> $HEADER
grep ShellIntegrationVersion= Resources/shell_integration/iterm2_shell_integration.* | sed -n 's/^.*ShellIntegrationVersion=\([^;]*\).*shell=\([a-z]*\).*$/    @"\2": @\1,/p' >> $HEADER
echo "};" >> $HEADER

